apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-repo-cache
  namespace: jenkins
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
