# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

# Config for NFS Server
Vagrant.configure("2") do |cf|

  # NFS Server
  cf.vm.define "nfs-server" do |nfs|
    nfs.vm.box = "archlinux/archlinux"
    nfs.vm.hostname = "nfs-server.example.com"
   
    nfs.vm.network "private_network", ip: "172.16.16.99"

    nfs.vm.provider :virtualbox do |v|
      v.name    = "nfs-server"
      v.memory  = 256
      v.cpus    = 1
    end
  
    nfs.vm.provider :libvirt do |v|
      v.qemu_use_session = false
      v.memory  = 256
      v.nested  = true
      v.cpus    = 1
    end
    
    nfs.vm.provision "shell",path: "bootstrap_nfs.sh"
  end
end

